### ISSUE TITLE
Trouble with gubbins_consensus_update_header

### ISSUE THREAD

**Issue by josiah-liew** [BioinformaticsPlatformWIV-ISP/PACU#1]
Greetings,

I am struggling to make PACU work with ONT reads for some Salmonella isolates we have. I appreciate any advice you may have. The test script for PACU is able to proceed. 

The log is as follows:
[camel.log](https://github.com/user-attachments/files/15542418/camel.log)

The errors are described as follows: 
![image](https://github.com/BioinformaticsPlatformWIV-ISP/PACU/assets/76540799/db539db0-9dfd-4e39-ab1a-e8a789ad2ada)

Looking forward to your feedback. Thank you! 

Josiah

**Comment by BioinformaticsPlatformWIV-ISP** [comment]
Dear Josiah,

Thank you for using PACU! The error is hidden a bit higher up in the log:
`ValueError in file /home/gs2/miniconda3/envs/pacu/lib/python3.10/site-packages/pacu/resources/snp_workflow.smk, line 195:
More than one sequence found` 

The workflow supports only a single sequence in the reference genome. Make sure you use a closed genome without plasmid sequences as the reference (in FASTA format). 

I'll add a check at the beginning of the pipeline to make the error message clearer.

Best regards,
Bert

**Comment by josiah-liew** [comment]
Thank you, Bert. The workflow worked great

Best,
Josiah
