### ISSUE TITLE
Summary of final SNP sites

### ISSUE THREAD

**Issue by HughCottingham** [BioinformaticsPlatformWIV-ISP/PACU#2]
Hi, thanks for writing this it was easy to install and run.

Whereabouts can I find information on the position of each final SNP included in the snp_matrix.fasta file in the reference genome? In my case I noticed that while each sequence in the snp_matrix.fasta file was 62 bases long, there were 72 unique SNP sites across the vcf files in output/vcf, all of which were above the minimum quality score. So I am interested in looking into which of the 72 didn't make it in to the final fasta file and why. I double checked that none of these sites were present in the gubbins.bed, selected.bed, merged.bed, low_depth.bed or empty_phages.bed files in the work directory.

**Comment by BertBog** [comment]
Hey Hugh,

Thanks for your message! I think in your case, the distance filter may have removed some additional SNPs that were located too close together If you set the `--min-snp-dist` parameter to 0, you can disable this filtering step. 

But I agree that a file with the final positions of the SNP matrix is a good feature and I have added it to the code. I have included this functionality in the new version I have just released on pip (v0.0.6). The Bioconda installation should also be updated automatically, but this may take a while. 
 
For a quick and dirty solution, you can put a debugging statement here to log the positions:
https://github.com/BioinformaticsPlatformWIV-ISP/PACU/blob/121217e4410a351137f6db6fb02db7909d6055c7/pacu/app/utils/snpmatrixutils.py#L66

Something like: 
```
    for pos, _ in sorted(nucl_by_position.items()):
        print('\t'.join([pos.contig, str(pos.position)]))
```

Please let me know if you have further questions.

Best,
Bert

**Comment by HughCottingham** [comment]
Thanks heaps Bert, this was really helpful. 

Using the updated 0.0.6 version and the associated snp_positions.tsv table I was able to identify 13 SNP calls present in the vcf files that didn't make it into the final matrix. As you suggested, 7/13 were due to being less than 10 bp away from each other. One was due to quality less than 25. However, I am struggling to understand the remaining five - I skipped gubbins when I reran it, and I manually checked the phage.bed and depth files to ensure depth >=5 for every isolate. Any ideas on what else might be going on? If it's not too difficult, it would be great to include some information in the output summarising which SNPs from the output/vcf files were filtered at each step.

Hugh

**Comment by BertBog** [comment]
Hey Hugh,

Could it be that the same SNP is found in all datasets? In that case the position will be omitted from the final SNP matrix. Otherwise, if you could provide me the VCF files I can have a look to see what is going on.

Best,
Bert

**Comment by HughCottingham** [comment]
Ahh I just found filtering metrics you used in the header of the vcf files and the associated calls in the INFO column! Turns out it was the af filter command that was doing it in my case. Thanks a lot for your help, Bert.
Hugh
